### ISSUE TITLE
publish to maven central?

### ISSUE THREAD

**Issue by maxandersen** [beothorn/javaflame#94]
today you can use it directly with jbang like this:

`jbang --javaagent https://github.com/beothorn/javaflame/releases/download/v23.0.0/javaAgent.jar <yourapp>`

that will fetch it from github.

would be nice to have the agent in maven central to get mirroring "for free".and you could do just:

`jbang --javaagent com.something.beothorn:javaflame:RELEASE <yourapp>`

similar could be easier fetch with gradle and maven for running.

**Comment by beothorn** [comment]
Done, I am not familiar with jbang but it is now deployed on maven central.
Please pay attention that now there are versions for jvms 8, 11 and 21. 
Previously it only worked with java 8.
https://repo.maven.apache.org/maven2/com/github/beothorn/javaFlame/25.0.0/
