### ISSUE TITLE
default output directory is "unpredictable"

### ISSUE THREAD

**Issue by maxandersen** [beothorn/javaflame#95]
atm. it seems the output directory is temporary file location by default.

Would it not make more sense to use current working directory?

See the diff here:
`jbang --java 11 --javaagent com.github.beothorn:javaFlame:25.0.0:java8 env@jbangdev` where I use default it ends up at:

`/var/folders/rb/jl238yks5xg62d0brw32jbd40000gn/T/javaflame2973571343775011421/1728207267175_snap/index.html`

but
`jbang --java 11 --javaagent com.github.beothorn:javaFlame:25.0.0:java8=out:. env@jbangdev` where I explicitly use . of output I get it `./1728207136264_snap/index.html'` 

That seems to be more sensible.

**Comment by beothorn** [comment]
Thanks, that makes more sense. Starting from version 27, the default output will be on the working directory in a javaflame directory.  
The timestamp is also being dropped (this information is already present on the page anyway).
Relative folders are now also working.  

This issue will be closed on release 27.
