### ISSUE TITLE
agent blocks exit

### ISSUE THREAD

**Issue by maxandersen** [beothorn/javaflame#97]
when trying to use flamegraph with small utilities i.e.

`jbang --java 21 --javaagent com.github.beothorn:javaFlame:25.0.0:java8 env@jbangdev`

then the javaagent seem to block exit.

i.e. ` jbang env@jbangdev` just exits just fine.

**Comment by beothorn** [comment]
I double checked the javaflame snapshot thread is daemon.

That said, the calls to capture the values happens in the very same thread the function call is happening and is synchronous.
So if just adding an entry to the stack is too slow, then it will block, as adding the entry to the stack is code that was injected at the start of the function. 
There is space for optimizations to be done, but the real issue I think is the filter that is too broad.

For the next version, if no filter is informed, version 26 tries to find out what is the package for the main class and use that as filter instead.

In future versions, maybe if the capture is too large some failure or something else should be triggered.
I can see how maybe introducing some asynchronicity could also help speed things a lot, but this would be for the far future.

 `jbang --java 21 --javaagent com.github.beothorn:javaFlame:26.0.0:java8 env@jbangdev` runs fine now

Thanks a lot Max! :)
